input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["meteo_api"]
    codec => json
  }
}

filter {
  date {
    match => ["meteo_hour", "yyyy-MM-dd'T'HH:mm"]
    target => "meteo_hour"
    timezone => "Europe/Paris"
  }

  mutate {
    add_field => { "search_text" => "%{city} %{source}" }
    convert => {
      "temperature_2m" => "float"
      "precipitation" => "float"
      "wind_speed_10m" => "float"
      "[location][lat]" => "float"
      "[location][lon]" => "float"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "meteo-%{+YYYY.MM.dd}"
  }
  # debug utile
  stdout { codec => rubydebug }
}
